const SUPABASE_URL = 'https://kmgbpmyaqigfgcbhqodr.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZ2JwbXlhcWlnZmdjYmhxb2RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwNjI1MzgsImV4cCI6MjEwMjYzODUzOH0.JymlpPWNLpCHrmzwLK2AmKj1Vm0l3S1r4dUawipum88';

const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
